name: Bug Report
description: A Regular Bug Report
body:
  - type: markdown
    attributes:
      value: |
        Describe the issue
  - type: textarea
    id: description
    attributes:
      label: ""
