name: Regression
description: A bug report about a regression (i.e. something that used to work, but no longer does)
title: "[Regression]: "
labels: ["regression"]

body:
  - type: input
    id: working
    attributes:
      label: Working Version
      description: This can be a version number (e.g. 13.0.0) or a git hash (d7b669b3a30)
      placeholder:
    validations:
      required: true
  - type: input
    id: not-working
    attributes:
      label: Not Working Version
      description: This can be a version number (e.g. 13.0.0) or a git hash (d7b669b3a30)
      placeholder:
    validations:
      required: true
  - type: input
    id: cmake
    attributes:
      label: CMake Args
      description: If known, which cmake arguments were used for your build of LLVM.
      placeholder:
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder:
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
    validations:
      required: true

