name: Stable Backport Automation

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  check-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check comment
        run: echo ${{ github.event.comment.body }} | grep '^cherry-pick:'
     
  create-pull-request:
    runs-on: ubuntu-latest
    needs: check-comment
    steps:
      - name: Set job variables
        id: vars
        run: |
          echo ::set-output name=pr-head-branch::issue-${{ github.event.issue.number }}-pr
          echo ::set-output name=pr-base-branch::release/11.x
          echo ::set-output name=cherry-pick-commit::`echo ${{ github.event.comment.body }} | cut -d : -f 2 | tr -d ' '`

      - name: Checkout code
        if: startswith(github.event.comment.body, 'cherry-pick:')
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: llvm/llvm-project
          ref: ${{ steps.vars.outputs.pr-base-branch }}

      - name: Fetch necessary branches
        if: startswith(github.event.comment.body, 'cherry-pick:')
        run: |
          git fetch origin master
          if git ls-remote --exit-code -h https://github.com/${{ github.repository }} ${{ steps.vars.outputs.pr-head-branch }}; then
            git fetch https://github.com/${{ github.repository }} ${{ steps.vars.outputs.pr-head-branch }}:${{ steps.vars.outputs.pr-head-branch }}
            git checkout ${{ steps.vars.outputs.pr-head-branch }}
          fi
      - name: Set up git
        run: |
          git config --global user.name "llvmbot"
          git config --global user.email "llvmbot@llvm.org"

      - name: Cherry-pick commit
        if: startswith(github.event.comment.body, 'cherry-pick:')
        run: git cherry-pick -x ${{ steps.vars.outputs.cherry-pick-commit }}

      - name: Add cherry-pick failed comment
        if: failure()
        uses: actions/github-script@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          args: comment "Cherry pick of ${{ steps.vars.outputs.cherry-pick-commit }} failed"

      - name: Push Code
        if: startswith(github.event.comment.body, 'cherry-pick:')
        run: git push https://${{ github.token }}@github.com/${{ github.repository }} HEAD:${{ steps.vars.outputs.pr-head-branch }}

      - name: Add branch name to issue
        uses: actions/github-script@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          args: "comment branch: ${{ steps.vars.outputs.pr-head-branch }}"
#      - name: Create pull request
#        if: startswith(github.event.comment.body, 'cherry-pick:')
#        uses: tstellar/actions/create-pull-request@pull-request
#        id: pull_request
#        with:
#          owner: tstellar
#          repo: llvm-project
#          title: "Backport patches from issue #${{ github.event.issue.number }}"
#          head: ${{ steps.vars.outputs.pr-head-branch }}
#          base: ${{ steps.vars.outputs.pr-base-branch }}
          
#      - name: Add link to pull request
#        uses: actions/github@v1.0.0
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        with:
#          args: "comment pull-request: #${{ steps.pull_request.outputs.pull_number }}"
