name: Stable Backport Automation

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit
        if: startswith(github.event.comment.body, 'cherry-pick:')
        id: cherry-commit
        run: "echo ::set-output name=hash::`echo ${{ github.event.comment.body }} | cut -d : -f 2 | tr -d ' '`"

      - name: Checkout code
        if: startswith(github.event.comment.body, 'cherry-pick:')
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Cherry-pick commit
        if: startswith(github.event.comment.body, 'cherry-pick:')
        run: git cherry-pick ${{ steps.cherry-commit.outputs.hash }}
        
      - name: Push Code
        if: startswith(github.event.comment.body, 'cherry-pick:')
        run: git push https://${{ github.token }}@github.com/${{ github.repository }} HEAD:master-${{ github.event.issue.number }}
        
      - name: Create pull request
        if: startswith(github.event.comment.body, 'cherry-pick:')
        run: true
