name: Stable Backport Automation

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event
        run: echo ${{ github.event.comment.body }}

