name: Stable Backport Automation

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event
        run: echo ${{ github.event.comment.body }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push
        run: git push https://${{ github.token }}@github.com/${{ github.repository }} HEAD:master-${{ github.event.issue.number }}
        

