name: Release Workflow - Create Pull Request

on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    if: startswith(github.event.comment.body, '/branch')

    steps:
      - name: Setup Environment
        run:  |
          curl -O -L https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/llvm/utils/git/github-automation.py
          chmod a+x github-automation.py
          pip install PyGithub GitPython

      - name: Create Pull Request
        run: |
          ./github-automation.py \
          --token ${{ secrets.RELEASE_WORKFLOW_PUSH_SECRET }} \
          release-workflow \
          --issue-number ${{ github.event.issue.number }} \
          auto

