name: Release Workflow

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  backport-commits:
    name: Backport Commits
    runs-on: ubuntu-latest
    if: startswith(github.event.comment.body, '/cherry-pick')

    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          fetch-depth: 0

      - name: Setup Environment
        run: |
          pip install PyGithub
          branch=`./llvm/utils/git/github-automation.py release-workflow print-release-branch`
          git checkout $branch
          ./llvm/utils/git/github-automation.py setup-llvmbot-git

      - name: Backport Commits
        run: |
          ./llvm/utils/git/github-automation.py
          --token ${{ secrets.RELEASE_WORKFLOW_PUSH_SECRET }} \
          release-workflow \
          --issue-number ${{ github.event.issue.number }} \
          auto

  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    if: startswith(github.event.comment.body, '/branch')

    steps:
      - name: Setup Environment
        run:  |
          curl -O -L https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/llvm/utils/git/github-automation.py
          chmod a+x github-automation.py
          pip install PyGithub

      - name: Create Pull Request
        run: |
          ./github-automation.py \
          --token ${{ secrets.RELEASE_WORKFLOW_PUSH_SECRET }} \
          release-automation \
          --issue-number ${{ github.event.issue.number }} \
          auto

