name: Release Task

on:
  push:
    tags:
      - 'llvmorg-[0-9.]*'

jobs:
  runs-on: ubuntu-latest
  release_tasks:
    - name: Validate Tag
      if: '${{ github.event.pusher }} != "tstellar"'
      run: false

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"


        #    - name: Parse Tag
        #      run: 
        #
        #    - name: Checkout LLVM
        #      uses: actions/checkout@v1

        #    - name:  

