name: Release Task

on:
  push:
    tags:
      # The regex support here is limited, so just match everything that starts with llvmorg- and filter later.
      - 'llvmorg-*'

jobs:
  release_tasks:
    runs-on: ubuntu-latest
    steps:


      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Validate Tag
        run: |
          test "${{ github.actor }}" = "tstellar"
          echo "${{ github.ref }}" | grep -e 'llvmorg-[0-9.]\+\(-rc[0-9]\)\?'$

        #    - name: Parse Tag
        #      run: 
        #
        #    - name: Checkout LLVM
        #      uses: actions/checkout@v1

        #    - name:  

