name: Release Backport - Pull Request

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    if: startswith(github.event.comment.body, '/branch')

    steps:
      - name: Verify Action
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Failed to cherry-pick: ${{ steps.backport.outputs.failed-commit }}'
            })

      - name: Dispatch workflow
        uses: actions/github-script@v3
        with:
          script: |
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "release-workflow.yml",
              ref: main
            })
