name: Release Workflow

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  backport-commits:
    name: Backport Commits
    runs-on: ubuntu-latest
    if: startswith(github.event.comment.body, '/cherry-pick')

    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          fetch-depth: 0

      - name: Setup Environment
        run: |
          pip install PyGithub GitPython
          #FIXME: TEMP
          curl -O -L https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/llvm/utils/git/github-automation.py
          chmod a+x github-automation.py
          mv github-automation.py llvm/utils/git/
          #FIXME
          branch=`./llvm/utils/git/github-automation.py --token ${{ github.token }} release-workflow --issue-number ${{ github.event.issue.number }} print-release-branch`
          git checkout $branch
          ./llvm/utils/git/github-automation.py --token ${{ github.token }} setup-llvmbot-git

      - name: Backport Commits
        run: |
          printf "${{ github.event.comment.body }}" |
          ./llvm/utils/git/github-automation.py \
          --token ${{ secrets.RELEASE_WORKFLOW_PUSH_SECRET }} \
          release-workflow \
          --branch-repo tstellar/llvm-project \
          --issue-number ${{ github.event.issue.number }} \
          auto
