name: test-matrix
on:
  # Uncomment to be able to trigger the workflow manually
  # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events
  workflow_dispatch: {}

  push: {}

jobs:
  find:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.assets.outputs.name_id_pairs }}
    steps:
      - name: find
        id: assets
        run: |
          input='[{"name": "hello", id:"world"},{"name": "hola", id:"mundo"}]'
          pairs=`echo $input | jq '[.[] | {name:.name, id:.id} ]' -rc`
          if [ "$pairs" == "" ]; then
            pairs='[]'
          fi
          echo '::set-output name=name_id_pairs::$pairs'
  
  foo:
    needs: find
    runs-on: ubuntu-latest
    strategy:
      matrix:
       cfg:
         - ${{ fromJson(needs.find.outputs.matrix) }}

    steps:
      - name: "step1"
        run: |
          echo "Name=${{ matrix.cfg.name }} ID=${{ matrix.cfg.id }}"